// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models {
    public enum AccessPackageCatalogType {
        [EnumMember(Value = "userManaged")]
        UserManaged,
        [EnumMember(Value = "serviceDefault")]
        ServiceDefault,
        [EnumMember(Value = "serviceManaged")]
        ServiceManaged,
        [EnumMember(Value = "unknownFutureValue")]
        UnknownFutureValue,
    }
}
