// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models {
    public enum AlertFeedback {
        [EnumMember(Value = "unknown")]
        Unknown,
        [EnumMember(Value = "truePositive")]
        TruePositive,
        [EnumMember(Value = "falsePositive")]
        FalsePositive,
        [EnumMember(Value = "benignPositive")]
        BenignPositive,
        [EnumMember(Value = "unknownFutureValue")]
        UnknownFutureValue,
    }
}
