// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models {
    public enum AppKeyCredentialRestrictionType {
        [EnumMember(Value = "asymmetricKeyLifetime")]
        AsymmetricKeyLifetime,
        [EnumMember(Value = "unknownFutureValue")]
        UnknownFutureValue,
    }
}
