// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models {
    public enum AssignmentType {
        [EnumMember(Value = "required")]
        Required,
        [EnumMember(Value = "recommended")]
        Recommended,
        [EnumMember(Value = "unknownFutureValue")]
        UnknownFutureValue,
    }
}
