// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models {
    public enum AuthenticationPhoneType {
        [EnumMember(Value = "mobile")]
        Mobile,
        [EnumMember(Value = "alternateMobile")]
        AlternateMobile,
        [EnumMember(Value = "office")]
        Office,
        [EnumMember(Value = "unknownFutureValue")]
        UnknownFutureValue,
    }
}
