// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models {
    public enum AuthenticationProtocol {
        [EnumMember(Value = "wsFed")]
        WsFed,
        [EnumMember(Value = "saml")]
        Saml,
        [EnumMember(Value = "unknownFutureValue")]
        UnknownFutureValue,
    }
}
