// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models {
    public enum AuthenticationMethodsPolicyMigrationState {
        [EnumMember(Value = "preMigration")]
        PreMigration,
        [EnumMember(Value = "migrationInProgress")]
        MigrationInProgress,
        [EnumMember(Value = "migrationComplete")]
        MigrationComplete,
        [EnumMember(Value = "unknownFutureValue")]
        UnknownFutureValue,
    }
}
