// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models {
    public enum AuthenticationMethodKeyStrength {
        [EnumMember(Value = "normal")]
        Normal,
        [EnumMember(Value = "weak")]
        Weak,
        [EnumMember(Value = "unknown")]
        Unknown,
    }
}
