// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models {
    public enum BinaryOperator {
        [EnumMember(Value = "or")]
        Or,
        [EnumMember(Value = "and")]
        And,
    }
}
