// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models {
    public enum CalendarSharingActionType {
        [EnumMember(Value = "accept")]
        Accept,
    }
}
