// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models {
    public enum ChatMessagePolicyViolationDlpActionTypes {
        [EnumMember(Value = "none")]
        None,
        [EnumMember(Value = "notifySender")]
        NotifySender,
        [EnumMember(Value = "blockAccess")]
        BlockAccess,
        [EnumMember(Value = "blockAccessExternal")]
        BlockAccessExternal,
    }
}
