// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models {
    public enum ChatMessagePolicyViolationUserActionTypes {
        [EnumMember(Value = "none")]
        None,
        [EnumMember(Value = "override")]
        Override,
        [EnumMember(Value = "reportFalsePositive")]
        ReportFalsePositive,
    }
}
