// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models {
    public enum ChatMessageImportance {
        [EnumMember(Value = "normal")]
        Normal,
        [EnumMember(Value = "high")]
        High,
        [EnumMember(Value = "urgent")]
        Urgent,
        [EnumMember(Value = "unknownFutureValue")]
        UnknownFutureValue,
    }
}
