// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models {
    public enum CloudAppSecuritySessionControlType {
        [EnumMember(Value = "mcasConfigured")]
        McasConfigured,
        [EnumMember(Value = "monitorOnly")]
        MonitorOnly,
        [EnumMember(Value = "blockDownloads")]
        BlockDownloads,
        [EnumMember(Value = "unknownFutureValue")]
        UnknownFutureValue,
    }
}
