// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models {
    public enum ConditionalAccessExternalTenantsMembershipKind {
        [EnumMember(Value = "all")]
        All,
        [EnumMember(Value = "enumerated")]
        Enumerated,
        [EnumMember(Value = "unknownFutureValue")]
        UnknownFutureValue,
    }
}
