// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models {
    public enum ConditionalAccessPolicyState {
        [EnumMember(Value = "enabled")]
        Enabled,
        [EnumMember(Value = "disabled")]
        Disabled,
        [EnumMember(Value = "enabledForReportingButNotEnforced")]
        EnabledForReportingButNotEnforced,
    }
}
