// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models {
    public enum ConnectedOrganizationState {
        [EnumMember(Value = "configured")]
        Configured,
        [EnumMember(Value = "proposed")]
        Proposed,
        [EnumMember(Value = "unknownFutureValue")]
        UnknownFutureValue,
    }
}
