// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models {
    public enum DelegatedAdminRelationshipOperationType {
        [EnumMember(Value = "delegatedAdminAccessAssignmentUpdate")]
        DelegatedAdminAccessAssignmentUpdate,
        [EnumMember(Value = "unknownFutureValue")]
        UnknownFutureValue,
    }
}
