// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models {
    public enum DelegateMeetingMessageDeliveryOptions {
        [EnumMember(Value = "sendToDelegateAndInformationToPrincipal")]
        SendToDelegateAndInformationToPrincipal,
        [EnumMember(Value = "sendToDelegateAndPrincipal")]
        SendToDelegateAndPrincipal,
        [EnumMember(Value = "sendToDelegateOnly")]
        SendToDelegateOnly,
    }
}
