// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models {
    public enum EducationAddedStudentAction {
        [EnumMember(Value = "none")]
        None,
        [EnumMember(Value = "assignIfOpen")]
        AssignIfOpen,
        [EnumMember(Value = "unknownFutureValue")]
        UnknownFutureValue,
    }
}
