// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models {
    public enum ExpirationPatternType {
        [EnumMember(Value = "notSpecified")]
        NotSpecified,
        [EnumMember(Value = "noExpiration")]
        NoExpiration,
        [EnumMember(Value = "afterDateTime")]
        AfterDateTime,
        [EnumMember(Value = "afterDuration")]
        AfterDuration,
    }
}
