// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models {
    public enum GiphyRatingType {
        [EnumMember(Value = "strict")]
        Strict,
        [EnumMember(Value = "moderate")]
        Moderate,
        [EnumMember(Value = "unknownFutureValue")]
        UnknownFutureValue,
    }
}
