// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models {
    public enum GroupType {
        [EnumMember(Value = "unifiedGroups")]
        UnifiedGroups,
        [EnumMember(Value = "azureAD")]
        AzureAD,
        [EnumMember(Value = "unknownFutureValue")]
        UnknownFutureValue,
    }
}
