// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models {
    public enum IdentityUserFlowAttributeType {
        [EnumMember(Value = "builtIn")]
        BuiltIn,
        [EnumMember(Value = "custom")]
        Custom,
        [EnumMember(Value = "required")]
        Required,
        [EnumMember(Value = "unknownFutureValue")]
        UnknownFutureValue,
    }
}
