// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models {
    public enum InferenceClassificationType {
        [EnumMember(Value = "focused")]
        Focused,
        [EnumMember(Value = "other")]
        Other,
    }
}
