// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models {
    public enum MicrosoftAuthenticatorAuthenticationMode {
        [EnumMember(Value = "deviceBasedPush")]
        DeviceBasedPush,
        [EnumMember(Value = "push")]
        Push,
        [EnumMember(Value = "any")]
        Any,
    }
}
