// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models {
    public enum MicrosoftStoreForBusinessLicenseType {
        [EnumMember(Value = "offline")]
        Offline,
        [EnumMember(Value = "online")]
        Online,
    }
}
