// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models {
    public enum PermissionType {
        [EnumMember(Value = "application")]
        Application,
        [EnumMember(Value = "delegated")]
        Delegated,
        [EnumMember(Value = "delegatedUserConsentable")]
        DelegatedUserConsentable,
    }
}
