// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models {
    public enum PersistentBrowserSessionMode {
        [EnumMember(Value = "always")]
        Always,
        [EnumMember(Value = "never")]
        Never,
    }
}
