// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models {
    public enum ScopeOperatorMultiValuedComparisonType {
        [EnumMember(Value = "All")]
        All,
        [EnumMember(Value = "Any")]
        Any,
    }
}
