// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models {
    public enum ScopeOperatorType {
        [EnumMember(Value = "Binary")]
        Binary,
        [EnumMember(Value = "Unary")]
        Unary,
    }
}
