// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models {
    public enum SelectionLikelihoodInfo {
        [EnumMember(Value = "notSpecified")]
        NotSpecified,
        [EnumMember(Value = "high")]
        High,
    }
}
