// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models {
    public enum SettingSourceType {
        [EnumMember(Value = "deviceConfiguration")]
        DeviceConfiguration,
        [EnumMember(Value = "deviceIntent")]
        DeviceIntent,
    }
}
