// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models {
    public enum SigninFrequencyType {
        [EnumMember(Value = "days")]
        Days,
        [EnumMember(Value = "hours")]
        Hours,
    }
}
