// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models {
    public enum SignInFrequencyAuthenticationType {
        [EnumMember(Value = "primaryAndSecondaryAuthentication")]
        PrimaryAndSecondaryAuthentication,
        [EnumMember(Value = "secondaryAuthentication")]
        SecondaryAuthentication,
        [EnumMember(Value = "unknownFutureValue")]
        UnknownFutureValue,
    }
}
