// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models {
    public enum SynchronizationTaskExecutionResult {
        [EnumMember(Value = "Succeeded")]
        Succeeded,
        [EnumMember(Value = "Failed")]
        Failed,
        [EnumMember(Value = "EntryLevelErrors")]
        EntryLevelErrors,
    }
}
