// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models {
    public enum TeamworkTagType {
        [EnumMember(Value = "standard")]
        Standard,
        [EnumMember(Value = "unknownFutureValue")]
        UnknownFutureValue,
    }
}
