// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models {
    public enum TeamVisibilityType {
        [EnumMember(Value = "private")]
        Private,
        [EnumMember(Value = "public")]
        Public,
        [EnumMember(Value = "hiddenMembership")]
        HiddenMembership,
        [EnumMember(Value = "unknownFutureValue")]
        UnknownFutureValue,
    }
}
