// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models {
    public enum ThreatAssessmentResultType {
        [EnumMember(Value = "checkPolicy")]
        CheckPolicy,
        [EnumMember(Value = "rescan")]
        Rescan,
        [EnumMember(Value = "unknownFutureValue")]
        UnknownFutureValue,
    }
}
