// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models {
    public enum VolumeType {
        [EnumMember(Value = "operatingSystemVolume")]
        OperatingSystemVolume,
        [EnumMember(Value = "fixedDataVolume")]
        FixedDataVolume,
        [EnumMember(Value = "removableDataVolume")]
        RemovableDataVolume,
        [EnumMember(Value = "unknownFutureValue")]
        UnknownFutureValue,
    }
}
