// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models {
    public enum WorkforceIntegrationEncryptionProtocol {
        [EnumMember(Value = "sharedSecret")]
        SharedSecret,
        [EnumMember(Value = "unknownFutureValue")]
        UnknownFutureValue,
    }
}
