// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models.CallRecords {
    public enum FailureStage {
        [EnumMember(Value = "unknown")]
        Unknown,
        [EnumMember(Value = "callSetup")]
        CallSetup,
        [EnumMember(Value = "midcall")]
        Midcall,
        [EnumMember(Value = "unknownFutureValue")]
        UnknownFutureValue,
    }
}
