// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models.CallRecords {
    public enum MediaStreamDirection {
        [EnumMember(Value = "callerToCallee")]
        CallerToCallee,
        [EnumMember(Value = "calleeToCaller")]
        CalleeToCaller,
    }
}
