// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models.Security {
    public enum DataSourceContainerStatus {
        [EnumMember(Value = "active")]
        Active,
        [EnumMember(Value = "released")]
        Released,
        [EnumMember(Value = "unknownFutureValue")]
        UnknownFutureValue,
    }
}
