// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models.Security {
    public enum GoogleCloudLocationType {
        [EnumMember(Value = "unknown")]
        Unknown,
        [EnumMember(Value = "regional")]
        Regional,
        [EnumMember(Value = "zonal")]
        Zonal,
        [EnumMember(Value = "global")]
        Global,
        [EnumMember(Value = "unknownFutureValue")]
        UnknownFutureValue,
    }
}
