// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models.Security {
    public enum SourceType {
        [EnumMember(Value = "mailbox")]
        Mailbox,
        [EnumMember(Value = "site")]
        Site,
        [EnumMember(Value = "unknownFutureValue")]
        UnknownFutureValue,
    }
}
