// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GetUserClient.ApiClient.Models.ExternalConnectors {
    public enum AccessType {
        [EnumMember(Value = "grant")]
        Grant,
        [EnumMember(Value = "deny")]
        Deny,
        [EnumMember(Value = "unknownFutureValue")]
        UnknownFutureValue,
    }
}
